name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test basic setup
      run: |
        echo "=== Basic Setup Test ==="
        echo "✅ Repository checked out successfully"
        echo "📁 Current directory: $(pwd)"
        echo "📋 Repository contents:"
        ls -la
        echo "✅ Step 1 completed successfully"
        
    - name: Detect project structure
      run: |
        echo "=== Project Structure Analysis ==="
        echo "🔍 Checking for frontend source files..."
        if [ -d "ahp_frontend_src" ]; then
          echo "✅ Frontend source directory found"
          echo "📁 Frontend source contents:"
          ls -la ahp_frontend_src/ | head -10
        else
          echo "❌ Frontend source directory not found"
        fi
        
        echo "🔍 Checking for package.json..."
        if [ -f "ahp_package.json" ]; then
          echo "✅ Package configuration found"
          echo "📋 Package info:"
          head -10 ahp_package.json
        else
          echo "❌ Package configuration not found"
        fi
        
        echo "🔍 Checking for public files..."
        if [ -d "ahp_frontend_public" ]; then
          echo "✅ Public directory found"
          echo "📁 Public contents:"
          ls -la ahp_frontend_public/
        else
          echo "❌ Public directory not found"
        fi
        echo "✅ Step 2 completed successfully"
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ahp_package.json
        
    - name: Verify Node.js setup
      run: |
        echo "=== Node.js Environment Verification ==="
        echo "📦 Node.js version:"
        node --version
        echo "📦 npm version:"
        npm --version
        echo "🔍 Checking npm cache:"
        npm config get cache
        echo "✅ Step 3 completed successfully"