name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'ahp_frontend_public/**'
      - 'ahp_frontend_src/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ahp_frontend_public/**'
      - 'ahp_frontend_src/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Check frontend source
      run: |
        echo "Checking for frontend files..."
        ls -la
        if [ -d "ahp_frontend_public" ]; then
          echo "Found ahp_frontend_public directory"
          ls -la ahp_frontend_public/
        else
          echo "ahp_frontend_public directory not found"
          exit 1
        fi
        
    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        cp -r ahp_frontend_public/* deploy/
        echo "Build completed successfully"
        ls -la deploy/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4