name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'ahp_frontend_public/**'
      - 'ahp_frontend_src/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ahp_frontend_public/**'
      - 'ahp_frontend_src/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check frontend source
      run: |
        echo "Checking for frontend files..."
        ls -la
        if [ -d "ahp_frontend_src" ]; then
          echo "Found ahp_frontend_src directory (React source)"
          ls -la ahp_frontend_src/
        elif [ -d "ahp_frontend_public" ]; then
          echo "Found ahp_frontend_public directory (Static files)"
          ls -la ahp_frontend_public/
        else
          echo "No frontend directory found"
          exit 1
        fi
        
    - name: Build React App
      run: |
        if [ -f "ahp_package.json" ]; then
          echo "Building React app from source..."
          cp ahp_package.json package.json
          npm install
          
          # Create src directory and copy files
          mkdir -p src
          cp -r ahp_frontend_src/* src/
          
          # Create public directory
          mkdir -p public
          if [ -d "ahp_frontend_public" ]; then
            cp -r ahp_frontend_public/* public/
          fi
          
          # Build the app
          npm run build
          echo "React build completed"
          ls -la build/
        else
          echo "No package.json found, using static files"
        fi
        
    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        if [ -d "build" ]; then
          echo "Deploying built React app..."
          cp -r build/* deploy/
        elif [ -d "ahp_frontend_public" ]; then
          echo "Deploying static files..."
          cp -r ahp_frontend_public/* deploy/
        fi
        echo "Deployment files prepared"
        ls -la deploy/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4